export const ADDP_NAV_TYPE = 'ADDP_NAV_TYPE';
export const ADDP_SEARCH_INDEX_DATA = 'ADDP_SEARCH_INDEX_DATA';
export const ADDP_SERVICE_DETAIL = 'ADDP_SERVICE_DETAIL';
export const ADDP_SERVICE_METHOD = 'ADDP_SERVICE_METHOD';