server:
  port: 8100
spring:
  profiles:
    include: conf
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  resources:
    #静态资源文件路径
    static-locations: classpath:/static/
  redis:
    host: 59.110.234.213
  datasource:
    druid:
      max-wait: 3000
      min-idle: 1
      time-between-eviction-runs-millis: 1000

---
spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql=true:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: net.sf.log4jdbc.DriverSpy
    url: jdbc:log4jdbc:mysql://59.110.234.213:3306/addp-rpc?useSSL=false&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
  mvc:
    view:
      prefix: /
      suffix: .html
  devtools:
    livereload:
      enabled: false
logging:
  file: ./log/log.log
  level:
    root: info
---

---
spring:
  profiles: test
  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql=true:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://59.110.234.213:3306/addp-rpc?useSSL=false&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
logging:
  file: /opt/addp/logs/log.log
  level:
    root: info
---
---
spring:
  profiles: pro
  devtools:
    livereload:
      enabled: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://59.110.234.213:3306/addp-rpc?useSSL=false&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.jdbc.Driver
logging:
  file: /opt/addp/logs/log.log
---
