server:
  port: 8080
spring:
  profiles:
    include: conf
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  resources:
    #静态资源文件路径
    static-locations: classpath:/static/
  redis:
    host: 59.110.234.213
logging:
  level: debug
  file: ./log/addp.log
jingxun:
  web:
    addpBaseFile: /opt/addp/
